[workspace]
members = [".", "viewer"]
default-members = [".", "viewer"]

[package]
name = "copc-rs"
version = "0.1.0"
edition = "2018"
resolver = "2"
default-run = "copc-rs"

[dependencies]
las = { version = "0.7.4", features = ["laz"] }
