[workspace]
members = [".", "viewer"]
default-members = ["."]

[package]
name = "copc-rs"
version = "0.2.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"
resolver = "2"

description = "Cloud Optimized Point Cloud (COPC) reader."
homepage = "https://github.com/pka/copc-rs"
repository = "https://github.com/pka/copc-rs"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["lidar", "pointcloud", "copc", "las", "geo"]
exclude = [
    "tests/data",    
]

[dependencies]
byteorder = "1.4.3"
las = "0.8.1"
laz = "0.8.2"

[dev-dependencies]
http-range-client = { git = "https://github.com/pka/http-range-client", branch="seek-read", features = ["reqwest-sync", "logging"] }
env_logger = "0.10.0"
