[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

[features]
trace_tracy = ["bevy/trace_tracy"]

[dependencies]
bevy = { version = "0.7.0-dev", git = "https://github.com/bevyengine/bevy", rev = "6f16580b8" }
copc-rs = { path = ".." }
bytemuck = "1.9.1"
